"""Empirical tuning for `settings.guardrails_factuality_min_score`.

Runs the FactualConsistency NLI scanner against:

  - 30 grounded answers (the positive cohort, generated by running the
    real RAG pipeline on `data/golden_test_set.csv`)
  - 30 deliberate hallucinations (`data/negative_test_set.csv`)

Prints a markdown table of (threshold, FPR, TPR, Youden's J) at fixed
0.05 steps from 0.05 to 0.50, plus two recommended thresholds:

  - Youden's J max — classic ROC operating point
  - Highest threshold with FPR ≤ 0.10 — operator-friendly "ship without
    annoying users" framing

The operator reads both numbers and picks. No CLI flags by design — if
you want a different sweep range, edit `THRESHOLDS` below.

The script bypasses `FactualConsistency.scan()` and re-uses the
scanner's `_tokenizer` and `_model` fields directly. Reason: the public
`.scan()` rounds predictions to 2 decimal places (factual_consistency.py
line 73), and only returns a `risk_score` that mixes the threshold into
the score we want to extract. There's no public alternative in
llm-guard 0.3.x. The lockfile pins llm-guard <1.0 so this stays stable
for the course's lifetime.

Usage:

    make tune-factuality

See `docs/plans/2026-04-29-feat-factuality-threshold-tuning-plan.md`
for the methodology and `docs/verifications/2026-04-29-factuality-threshold-tuning.md`
for the calibration that produced the current default.
"""

import csv
import json
import sys
from pathlib import Path

import torch
from llm_guard.output_scanners import FactualConsistency

from src.evaluation import build_eval_dataset, load_golden_set

# Sweep range — edit if you need different bounds.
THRESHOLDS: list[float] = [round(0.05 * i, 2) for i in range(1, 11)]  # 0.05..0.50

POSITIVES_PATH = Path("data/golden_test_set.csv")
NEGATIVES_PATH = Path("data/negative_test_set.csv")
FPR_BUDGET = 0.10


def _load_negatives() -> list[dict]:
    """Read the negative cohort. Fail loudly with a clear precondition
    error if the file is missing — generating it is a one-off REPL job
    documented in the verification report, not part of `make tune-factuality`.
    """
    if not NEGATIVES_PATH.exists():
        sys.exit(
            f"ERROR: {NEGATIVES_PATH} is missing. The negative cohort is "
            "generated by a one-off REPL session against gpt-4o-mini; see "
            "docs/verifications/2026-04-29-factuality-threshold-tuning.md "
            "for the prompt template."
        )
    with open(NEGATIVES_PATH, newline="") as f:
        return list(csv.DictReader(f))


def _build_extractor():
    """Instantiate FactualConsistency to load the model + tokenizer, then
    return a closure that yields raw entailment probability per pair.

    Mirrors llm_guard/output_scanners/factual_consistency.py:60-74 minus
    the 2dp rounding. Label order assumption: index 0 = entailment,
    index 1 = not_entailment (per scanner line 71). If LLM Guard ever
    swaps these, the output table will look wildly wrong and a glance
    at the data will show it — we don't add a defensive runtime
    assertion since the visual signal is stronger.
    """
    scanner = FactualConsistency(minimum_score=0.0)
    tokenizer = scanner._tokenizer
    model = scanner._model

    def entailment_score(reference: str, output: str) -> float:
        if reference.strip() == "":
            return -1.0  # mirror scanner's empty-prompt behavior
        tokens = tokenizer(
            output, reference, padding=True, truncation=True, return_tensors="pt"
        )
        tokens = {k: v.to(model.device) for k, v in tokens.items()}
        with torch.no_grad():
            logits = model(**tokens)["logits"][0]
            probs = torch.softmax(logits, -1).tolist()
        return float(probs[0])

    return entailment_score


def main() -> int:
    print("Loading positive cohort (running RAG pipeline against golden set)…")
    golden = load_golden_set(POSITIVES_PATH)
    positives_dataset = build_eval_dataset(golden)
    positives = [
        (q, a, " ".join(c))
        for q, a, c in zip(
            positives_dataset["question"],
            positives_dataset["answer"],
            positives_dataset["contexts"],
        )
    ]

    print("Loading negative cohort…")
    raw_negatives = _load_negatives()
    negatives = [
        (r["question"], r["hallucinated_answer"], " ".join(json.loads(r["contexts"])), r["negative_kind"])
        for r in raw_negatives
    ]

    print(f"Positives: {len(positives)}    Negatives: {len(negatives)}")
    print("Loading FactualConsistency scanner (NLI model)…")
    score = _build_extractor()

    print("Scoring positives…")
    pos_scores = [(q, score(src, ans)) for q, ans, src in positives]
    print("Scoring negatives…")
    neg_scores = [(q, kind, score(src, ans)) for q, ans, src, kind in negatives]

    # Sweep
    rows = []
    for t in THRESHOLDS:
        fpr = sum(1 for _, s in pos_scores if s < t) / len(pos_scores)
        tpr = sum(1 for _, _, s in neg_scores if s < t) / len(neg_scores)
        rows.append((t, fpr, tpr, tpr - fpr))

    print("\n## Threshold sweep\n")
    print("| threshold | FPR | TPR | Youden's J |")
    print("|-----------|-----|-----|------------|")
    for t, fpr, tpr, j in rows:
        print(f"| {t:.2f}      | {fpr:.2f} | {tpr:.2f} | {j:+.2f}      |")

    # Recommendations
    youden_t, *_, youden_j = max(((t, fpr, tpr, j) for t, fpr, tpr, j in rows), key=lambda r: r[3])
    fpr_budget_candidates = [(t, fpr, tpr, j) for t, fpr, tpr, j in rows if fpr <= FPR_BUDGET]
    if fpr_budget_candidates:
        budget_t, budget_fpr, budget_tpr, _ = max(fpr_budget_candidates, key=lambda r: r[0])
    else:
        budget_t = budget_fpr = budget_tpr = None

    print("\n## Recommended thresholds\n")
    print(f"- **Youden's J max:** threshold = {youden_t:.2f} (J = {youden_j:+.2f})")
    if budget_t is not None:
        print(
            f"- **Highest threshold with FPR ≤ {FPR_BUDGET:.2f}:** "
            f"threshold = {budget_t:.2f} (FPR = {budget_fpr:.2f}, TPR = {budget_tpr:.2f})"
        )
    else:
        print(f"- **Highest threshold with FPR ≤ {FPR_BUDGET:.2f}:** none — every threshold blocks more grounded answers than budget allows. Either tighten the cohort or accept a higher FPR.")

    # Outliers
    print("\n## Outliers\n")
    pos_low = [(q, s) for q, s in pos_scores if s <= 0.10]
    neg_high = [(q, kind, s) for q, kind, s in neg_scores if s >= 0.50]
    if pos_low:
        print("**Positives scoring ≤ 0.10** (these would be blocked at every meaningful threshold):")
        for q, s in pos_low:
            print(f"  - {s:.2f}  {q}")
    else:
        print("No positives scored ≤ 0.10 — clean.")
    print()
    if neg_high:
        print("**Negatives scoring ≥ 0.50** (these would slip through at every meaningful threshold):")
        for q, kind, s in neg_high:
            print(f"  - {s:.2f}  [{kind}]  {q}")
    else:
        print("No negatives scored ≥ 0.50 — clean.")

    # Quality gate
    easy_negs = [(q, s) for q, kind, s in neg_scores if kind == "easy"]
    failing_easy = [(q, s) for q, s in easy_negs if s > 0.30]
    if failing_easy:
        print(
            f"\n**Quality gate FAILED:** {len(failing_easy)}/{len(easy_negs)} "
            "easy negatives scored > 0.30. The negative dataset has weak entries "
            "and should be regenerated before the calibration is trusted."
        )
        for q, s in failing_easy:
            print(f"  - {s:.2f}  {q}")
        return 1
    print(f"\nQuality gate: all {len(easy_negs)} easy negatives ≤ 0.30 ✓")
    return 0


if __name__ == "__main__":
    sys.exit(main())
